version: '3.1'



services:
  postgres-db:
    container_name: postgres-base
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/java_base

  redis:
    image: redis
    ports:
      - "6379:6379"
  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"

  hazelcast:
    image: hazelcast/hazelcast:latest
    ports:
      - "5701:5701"
    environment:
      - HAZELCAST_NETWORK_PORT=5701  # Ensure this is set correctly
      - HAZELCAST_CLUSTER_NAME=dev

  management-center:
    image: hazelcast/management-center:latest
    ports:
      - "8080:8080"
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast

