server:
  port: 9050

grpc:
  client:
    greetingService:
      address: static://localhost:9065
      negotiation-type: plaintext
    duplicateService:
      address: static://localhost:9075
      negotiation-type: plaintext