syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.hazelcast.server.proto";
option java_outer_classname = "DuplicateProto";



message FindUUIDRequest {
  string uuid = 1;
}

message SaveRequest {
  string uuid = 1;
  CustomResponse custom = 2;
}

message ResponseWrapper {
  ResponseObject status = 1;
  CustomResponse custom = 2;
  map<string, Value> data = 3;
}

message ResponseObject {
  int32 code = 1;
  bool status = 2;
  string message = 3;
}

message CustomResponse {
  string uuid = 1;
  string transactionMessage = 2;
}



message Value {
  oneof kind {
    NullValue null_value = 1;
    double number_value = 2;
    string string_value = 3;
    bool bool_value = 4;
    Struct struct_value = 5;
    ListValue list_value = 6;
  }
}

enum NullValue {
  NULL_VALUE = 0;
}

message ListValue {
  repeated Value values = 1;
}

message Struct {
  map<string, Value> fields = 1;
}


service Duplicate {
  rpc QueryForMessage(FindUUIDRequest) returns (ResponseWrapper){}
  rpc SaveMessage(SaveRequest) returns (ResponseWrapper){}
}
