server:
  port: 9070

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/java_base
  cache:
    type: hazelcast
    instance-name: hazelcast-dev
    management-center:
      enabled: true
    network:
      port: 5701
      port-auto-increment: true
      join:
        multicast:
          enabled: true


cacheName: save-dto
cacheTTL: 30